version: "2"
services:

  db:
    image: influxdb:1.2-alpine
    ports:
      - 8083:8083
      - 8086:8086
    network_mode: "host"
    volumes:
      - ./influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf:z
      - ./influxdb/data:/var/lib/influxdb:z
    command: -config /etc/influxdb/influxdb.conf

  graf:
    image: chronograf:0.13.0
    ports:
      - 10000:10000
    volumes:
      - ./chronograf/conf/chronograf.conf:/etc/chronograf/chronograf.conf:z

  pg:
    image: postgres:9.2-alpine
    ports:
      - 5432:5432
    environment:
      - DEBUG=true
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql
