version: "3.3"

volumes:
  influx-data:
  grafana-data:
  pg-data:

services:
  traefik:
    image: traefik:v2.1
    ports:
      - "80:80"
      - "81:8080"
    volumes:
      - ./conf/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock

  influxdb:
    image: influxdb:1.7-alpine
    ports:
      - "8086:8086"
    volumes:
      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf:z
      - influx-data:/var/lib/influxdb:z
    command: -config /etc/influxdb/influxdb.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.arig.local`)"
    depends_on:
      - traefik

  chronograf:
    image: chronograf:1.8-alpine
    ports:
      - "8888:8888"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chronograf.rule=Host(`chronograf.arig.local`)"
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:6.7.1
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.arig.local`)"
    depends_on:
      - influxdb

  pg:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=true
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "0:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=arig@arig.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.arig.local`)"
    depends_on:
      - pg

  reader:
    image: arig/robots-reader:build-node-13
    ports:
      - "0:4100"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.reader-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.reader.rule=Host(`superviseur.arig.local`) && PathPrefix(`/api`)"
      - "traefik.http.routers.reader.middlewares=reader-stripprefix@docker"
    depends_on:
      - pg
      - grafana
      - influxdb
    volumes:
      - ../../java/robots/nerell-parent/nerell-simulator/logs:/logs/simulateur

  superviseur:
    image: arig/robots-supervisor:local
    ports:
      - "0:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.superviseur.rule=Host(`superviseur.arig.local`)"
    depends_on:
      - reader