version: "2.1"
services:
  traefik:
    image: containous/traefik:v1.3.7
    ports:
      - "80:80"
      - "81:8080"
    volumes:
      - ./traefik/conf/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/log:/var/log/traefik:z
      - /var/run/docker.sock:/var/run/docker.sock

  influxdb:
    image: influxdb:1.3-alpine
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf:z
      - ./influxdb/data:/var/lib/influxdb:z
    command: -config /etc/influxdb/influxdb.conf
    labels:
      - "traefik.enable=true"
      - "traefik.backend=influxdb"
      - "traefik.frontend.rule=Host:influxdb.arig.local"
    depends_on:
      - traefik

  chronograf:
    image: chronograf:1.3-alpine
    ports:
      - "8888:8888"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=chronograf"
      - "traefik.frontend.rule=Host:chronograf.arig.local"
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/lib:/var/lib/grafana
      - ./grafana/var:/var/log/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:grafana.arig.local"
    depends_on:
      - influxdb

  pg:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=true
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      - ./postgres:/var/lib/postgresql

  superviseur:
    image: arig/robots-supervisor:dev
    ports:
      - "0:80"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=superviseur"
      - "traefik.frontend.rule=Host:superviseur.arig.local"
    depends_on:
      - pg
      - grafana
