server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: robots
    static_configs:
      - targets:
          - localhost
        labels:
          robot: nerell-simu
          __path__: /var/log/nerell-simu/*-traces.log
